package Aggregator

const (
	MAC_SERVER                = "mac_srv"      // "mac_srv" : "1C:C1:DE:80:D1:41"
	MAC_CLIENT                = "mac_clnt"     // "mac_clnt" : "2C:41:38:B9:91:7A"
	SERVER_IP                 = "service_ip"   // "service_ip" : "65.55.252.167"
	SERVER_PORT               = "service_port" // "service_port" : 443
	PROTOCOL                  = "srv_protocol" // "srv_protocol" : "SSL"
	GROUP_ID                  = "group_id"     // "group_id" : "SSL"
	CLIENT_IP                 = "clnt_ip"      // "clnt_ip" : "192.168.1.48"
	CLIENT_PORT               = "clnt_port"    // "clnt_port" : 53376
	START_TIME                = "start"        // "startTime" : NumberLong(1495523779838616)
	END_TIME                  = "end"
	SERVER_IP6                = "service_ipv6"
	CLIENT_IP6                = "clnt_ipv6"
	ART                       = "art"
	RTT                       = "rtt"
	FROM_SRV_PCKTS            = "from_srv_pckts"
	FROM_SRV_PKTS             = "from_srv_pkts"
	FROM_SRV_BYTES            = "from_srv_bytes"
	FROM_SRV_PAYLOAD          = "from_srv_payload"
	FROM_CLNT_PKTS            = "from_clnt_pkts"
	FROM_CLNT_BYTES           = "from_clnt_bytes"
	FROM_CLNT_PAYLOAD         = "from_clnt_payload"
	RETRANS_PKTS_FROM_SRV     = "retrans_pkts_from_srv"
	RETRANS_BYTES_FROM_SRV    = "retrans_bytes_from_srv"
	RETRANS_PKTS_FROM_CLNT    = "retrans_pkts_from_clnt"
	RETRANS_BYTES_FROM_CLNT   = "retrans_bytes_from_clnt"
	STATE                     = "state"
	LOST_FROM_SRV             = "lost_from_srv"
	LOST_FROM_CLNT            = "lost_from_clnt"
	REORDER_FROM_SRV          = "reorder_from_srv"
	REORDER_BYTES_FROM_SRV    = "reorder_bytes_from_srv"
	REORDER_FROM_CLNT         = "reorder_from_clnt"
	REORDER_BYTES_FROM_CLNT   = "reorder_bytes_from_clnt"
	FRAGMENTS_FROM_SRV        = "fragments_from_srv"
	FRAGMENTS_BYTES_FROM_SRV  = "fragments_bytes_from_srv"
	FRAGMENTS_FROM_CLNT       = "fragments_from_clnt"
	FRAGMENTS_BYTES_FROM_CLNT = "fragments_bytes_from_clnt"
	CLIENT_CERTIFICATE        = "client_certificate"
	SERVER_CERTIFICATE        = "server_certificate"
	TOS                       = "tos"
	COS                       = "cos"
	CIF                       = "cif"
	HTTP_URL                  = "http_url"
	HTTP_METHOD               = "http_method"
	HTTP_RESPONSE             = "http_response"
	HTTP_CONTEXT              = "http_context"
	HTTP_FORWARDED            = "http_forwarded"
	HTTP_ORIGIN               = "http_origin"
	HTTP_COOKIE               = "http_cookie"
	HTTP_X_SESSION_TYPE       = "http_x_session_type"
	HTTP_USER_AGENT           = "http_user_agent"
	HTTP_ENCODING             = "http_encoding"
	VERSION                   = "version"
	VLAN                      = "vlan"
	MPLS                      = "mpls"

	// Protocols
	TIMESTAMP = "timestamp"
	PROTO     = "proto"
	PKTS      = "pkts"
	BYTES     = "bytes"
	OUT_PKTS  = "out_pkts"
	OUT_BYTES = "out_bytes"
	SESSIONS  = "sessions"

	// Dns
	DNS_NAME = "cname"
	TTL      = "ttl"
	COUNT    = "count"
	ADDR     = "addr"
	ADDRV6   = "addrv6"

	// Protocols types
	PROTOCOLS = "protos"
	DNS       = "dns"
	SSL       = "ssl"
	HTTP      = "http"
	TCP       = "tcp"
	UDP       = "udp"

	// Other
	BROADCAST                 = "255"
	DEFAULT_IP6_ROUTE         = "0:0:0:0:0:0:0:0"
	CERTIFICATE_DOMAIN_PREFIX = "*."
	www                       = "www."
	SHORT_VLAN                = 32767
)
